printWidth: 80
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
trailingComma: es5
bracketSpacing: true
arrowParens: avoid
proseWrap: preserve
htmlWhitespaceSensitivity: css
endOfLine: lf
plugins:
  - prettier-plugin-svelte
  - prettier-plugin-tailwindcss
overrides:
  - files: '*.svelte'
    options:
      parser: svelte
